#!/usr/bin/env php
<?php

namespace Differ;

    use PHPUnit\Framework\TestCase;

    use function Differ\Differ\genDiff;

    class DifferTest extends TestCase
    {
        public function testDifferStylish(): void
        {
            $path1 = realpath("tests/fixtures/file1.json");
            $path2 = realpath("tests/fixtures/file2.json");
            $expected = trim(file_get_contents(realpath("tests/fixtures/CorrectStylish.txt")));
            $this->assertEquals($expected, genDiff($path1, $path2));
            echo "Tests passed!";
        }
        public function testDifferPlain(): void
        {
            $path1 = realpath("tests/fixtures/file1.json");
            $path2 = realpath("tests/fixtures/file2.json");
            $expected = file_get_contents("tests/fixtures/CorrectPlain.txt");
            $this->assertEquals($expected, genDiff($path1, $path2, "plain"));
            echo "Tests passed!";
        }
        public function testDifferJsonFormat(): void
        {
            $path1 = realpath("tests/fixtures/file1.json");
            $path2 = realpath("tests/fixtures/file2.json");
            $expected = file_get_contents("tests/fixtures/CorrectJson.txt");
            $this->assertEquals($expected, genDiff($path1, $path2, "json"));
            echo "Tests passed!";
        }

    }
